### ISSUE TITLE
Crash on startup after adding account

### ISSUE THREAD

**Issue by jpjonte** [laurencedawson/sync-for-lemmy#153]
**Describe the bug**  
Sync crashes on startup after adding my feddit.de account. 

**Steps to Reproduce**  
1. Clear storage
2. Open Sync and do the setup
3. Log in to feddit.de account (not sure if the instance is relevant) 
4. Skip or do setup (doesn't matter) 
5. Close Sync completely
6. Open Sync again
7. Feed loads with the first post and Sync crashes within 1-2 seconds. 

**Expected behavior**  
Feed loads, Sync doesn't crash. 

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - Android: 13
 - Sync version: Beta 19

**Additional context**  
Worked fine until I changed my settings (hide on scroll => true) this morning. Since then it crashes even without changing any settings. 

Doesn't happen when I stick with the default lemmy.world anonymous account, although they're having issues right now and the feed isn't loading.

**Comment by mittensicle** [comment]
Same.

Device: Pixel 6 Pro
Android 13 TQ3A.230705.001
Sync version beta 19

**Comment by jpjonte** [comment]
This is the stack trace that shows up in logcat when Sync crashes:

```
FATAL EXCEPTION: main
Process: io.syncapps.lemmy_sync, PID: 24540
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
at pa.a.<init>(Actor.java:6)
at za.b.<init>(ActorsList.java:6)
at za.b.i(ActorsList.java:4)
at p7.b.g(CommunitiesManager.java:1)
at p7.b.<init>(CommunitiesManager.java:2)
at p7.b.d(CommunitiesManager.java:3)
at xa.a.u(ActorPickerConcatAdapter.java:1)
at xa.a.m(ActorPickerConcatAdapter.java:16)
at io.syncapps.lemmy_sync.ui.fragments.DrawerFragment.o2(DrawerFragment.java:17)
at androidx.fragment.app.Fragment.N2(Fragment.java:1)
at androidx.fragment.app.l.f(FragmentStateManager.java:26)
at androidx.fragment.app.l.m(FragmentStateManager.java:20)
at androidx.fragment.app.FragmentManager.e0(FragmentManager.java:34)
at androidx.fragment.app.FragmentManager.e1(FragmentManager.java:10)
at androidx.fragment.app.FragmentManager.b0(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.T(FragmentManager.java:9)
at androidx.fragment.app.FragmentManager.z(FragmentManager.java:4)
at androidx.fragment.app.e.c(Unknown Source:4)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:6)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at io.syncapps.lemmy_sync.ui.activities.BaseActivity.onStart(BaseActivity.java:2)
at io.syncapps.lemmy_sync.ui.activities.BaseMaterialActivity.onStart(BaseMaterialActivity.java:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
at android.app.Activity.performStart(Activity.java:8367)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3669)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
````

**Comment by laurencedawson** [comment]
Fixed.
