### ISSUE TITLE
Crashing loading a profile

### ISSUE THREAD

**Issue by lionirdeadman** [laurencedawson/sync-for-lemmy#209]
**Describe the bug**  
Crashes when clicking on a profile and now since Sync wants to load it on startup, it crashes at boot.

**Steps to Reproduce**  
1. Go to this profile https://beehaw.org/u/autotldr@lemmings.world

**Expected behavior**  
Show a profile

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - Android: 13
 - Sync version: beta 26

**Additional context**  
Here's the crash log:
```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230705.001/2023072600:user/release-keys
package: io.syncapps.lemmy_sync:26
process: io.syncapps.lemmy_sync
processUptime: 546 + 205 ms
installer: com.android.vending

java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at ta.a.<init>(Actor.java:6)
	at db.b.<init>(ActorsList.java:6)
	at db.b.g(ActorsList.java:4)
	at n7.t0.c(VisitedManager.java:2)
	at n7.t0.e(VisitedManager.java:4)
	at r8.n.<init>(LemmyPostsRequest.java:6)
	at wa.h.R0(PostsPresenterImpl.java:7)
	at wa.h.b(PostsPresenterImpl.java:11)
	at io.syncapps.lemmy_sync.ui.fragments.posts.BasePostsFragment.p2(BasePostsFragment.java:6)
	at androidx.fragment.app.Fragment.O2(Fragment.java:1)
	at androidx.fragment.app.l.f(FragmentStateManager.java:26)
	at androidx.fragment.app.l.m(FragmentStateManager.java:20)
	at androidx.fragment.app.FragmentManager.e0(FragmentManager.java:34)
	at androidx.fragment.app.FragmentManager.e1(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.b0(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.T(FragmentManager.java:9)
	at androidx.fragment.app.FragmentManager.z(FragmentManager.java:4)
	at androidx.fragment.app.e.c(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:6)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at io.syncapps.lemmy_sync.ui.activities.BaseActivity.onStart(BaseActivity.java:2)
	at io.syncapps.lemmy_sync.ui.activities.BaseMaterialActivity.onStart(BaseMaterialActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
	at android.app.Activity.performStart(Activity.java:8414)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3680)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by laurencedawson** [comment]
Can't reproduce this. Still having the same issue?

**Comment by laurencedawson** [comment]
Closing due to inactivity.
