### ISSUE TITLE
No posts shown after importing Sync for Reddit backup

### ISSUE THREAD

**Issue by Nothing4You** [laurencedawson/sync-for-lemmy#244]
**Describe the bug**  
After importing a Sync 4 Reddit backup into Sync 4 Lemmy it no longer shows any posts.
I believe this was originally imported on beta 26, on beta 27 I'm still seeing no posts.

**Steps to Reproduce**  
1. Import S4R backup into S4L
2. Restart app to apply as prompted
3. No posts shown anymore

**Expected behavior**  
Theme and other similar settings should be migrated.

**Screenshots**
<details>
<summary>screenshot</summary>

![image](https://github.com/laurencedawson/sync-for-lemmy/assets/3694534/09b0ee56-b1bf-4bc2-8642-5863368f9ceb)
</details>

**App:**
 - Sync version: beta 27
 - Sync variant: Ultra Deluxe

**Additional context**
<details>
<summary>logcat</summary>

```
Resources: Drawable io.syncapps.lemmy_sync:drawable/outline_arrow_upward_24 has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
Resources: java.lang.RuntimeException
Resources:     at android.content.res.Resources.getDrawable(Resources.java:899)
Resources:     at db.l.D(PostActionsTouchHelperCallback.java:1)
Resources:     at db.l.<init>(PostActionsTouchHelperCallback.java:6)
Resources:     at io.syncapps.lemmy_sync.ui.views.recycler.PostsRecyclerView.E2(PostsRecyclerView.java:4)
Resources:     at io.syncapps.lemmy_sync.ui.fragments.posts.VerticalPostsFragment.K3(VerticalPostsFragment.java:3)
Resources:     at io.syncapps.lemmy_sync.ui.fragments.posts.BasePostsFragment.U1(BasePostsFragment.java:3)
Resources:     at androidx.fragment.app.Fragment.x2(Fragment.java:4)
Resources:     at androidx.fragment.app.l.f(FragmentStateManager.java:15)
Resources:     at androidx.fragment.app.l.m(FragmentStateManager.java:20)
Resources:     at androidx.fragment.app.FragmentManager.e0(FragmentManager.java:34)
Resources:     at androidx.fragment.app.FragmentManager.e1(FragmentManager.java:10)
Resources:     at androidx.fragment.app.FragmentManager.b0(FragmentManager.java:4)
Resources:     at androidx.fragment.app.FragmentManager.T(FragmentManager.java:9)
Resources:     at androidx.fragment.app.FragmentManager.z(FragmentManager.java:4)
Resources:     at androidx.fragment.app.e.c(Unknown Source:4)
Resources:     at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:6)
Resources:     at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
Resources:     at io.syncapps.lemmy_sync.ui.activities.BaseActivity.onStart(BaseActivity.java:2)
Resources:     at io.syncapps.lemmy_sync.ui.activities.BaseMaterialActivity.onStart(BaseMaterialActivity.java:1)
Resources:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
Resources:     at android.app.Activity.performStart(Activity.java:8018)
Resources:     at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
Resources:     at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
Resources:     at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
Resources:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
Resources:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
Resources:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
Resources:     at android.os.Handler.dispatchMessage(Handler.java:106)
Resources:     at android.os.Looper.loop(Looper.java:223)
Resources:     at android.app.ActivityThread.main(ActivityThread.java:7664)
Resources:     at java.lang.reflect.Method.invoke(Native Method)
Resources:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
Resources:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Resources: Drawable io.syncapps.lemmy_sync:drawable/outline_arrow_downward_24 has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
Resources: java.lang.RuntimeException
Resources:     at android.content.res.Resources.getDrawable(Resources.java:899)
Resources:     at db.l.D(PostActionsTouchHelperCallback.java:2)
Resources:     at db.l.<init>(PostActionsTouchHelperCallback.java:10)
Resources:     at io.syncapps.lemmy_sync.ui.views.recycler.PostsRecyclerView.E2(PostsRecyclerView.java:4)
Resources:     at io.syncapps.lemmy_sync.ui.fragments.posts.VerticalPostsFragment.K3(VerticalPostsFragment.java:3)
Resources:     at io.syncapps.lemmy_sync.ui.fragments.posts.BasePostsFragment.U1(BasePostsFragment.java:3)
Resources:     at androidx.fragment.app.Fragment.x2(Fragment.java:4)
Resources:     at androidx.fragment.app.l.f(FragmentStateManager.java:15)
Resources:     at androidx.fragment.app.l.m(FragmentStateManager.java:20)
Resources:     at androidx.fragment.app.FragmentManager.e0(FragmentManager.java:34)
Resources:     at androidx.fragment.app.FragmentManager.e1(FragmentManager.java:10)
Resources:     at androidx.fragment.app.FragmentManager.b0(FragmentManager.java:4)
Resources:     at androidx.fragment.app.FragmentManager.T(FragmentManager.java:9)
Resources:     at androidx.fragment.app.FragmentManager.z(FragmentManager.java:4)
Resources:     at androidx.fragment.app.e.c(Unknown Source:4)
Resources:     at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:6)
Resources:     at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
Resources:     at io.syncapps.lemmy_sync.ui.activities.BaseActivity.onStart(BaseActivity.java:2)
Resources:     at io.syncapps.lemmy_sync.ui.activities.BaseMaterialActivity.onStart(BaseMaterialActivity.java:1)
Resources:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
Resources:     at android.app.Activity.performStart(Activity.java:8018)
Resources:     at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
Resources:     at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
Resources:     at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
Resources:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
Resources:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
Resources:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
Resources:     at android.os.Handler.dispatchMessage(Handler.java:106)
Resources:     at android.os.Looper.loop(Looper.java:223)
Resources:     at android.app.ActivityThread.main(ActivityThread.java:7664)
Resources:     at java.lang.reflect.Method.invoke(Native Method)
Resources:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
Resources:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
</details>

**Comment by laurencedawson** [comment]
Any chance of sharing your backup file?

**Comment by Nothing4You** [comment]
for privacy reasons I've removed 1,565 entries from `user_paint_ultra`, 118 entries from `visited`, 9 entries from `user_tags_ultra` as well as the contents of `editor_drafts`.
this reduced the file size from 102K to 14K and the cleaned version can be imported without breakage, so it probably wouldn't help to share.

fwiw, this is still reproducible on beta 29.

is there maybe an issue with importing large configs?
