### ISSUE TITLE
App crashes when viewing a Community and opening the main hamburger menu

### ISSUE THREAD

**Issue by Kurocon** [laurencedawson/sync-for-lemmy#36]
**Describe the bug**  
The app crashes when opening the main hamburger menu (top right) when viewing a community.

**Steps to Reproduce**  
1. Go to any community, i.e. from the sidebar, or by going to a post and to its community from there.
2. Press the hamburger icon in the top right (see image below)
4. App crashes

**Expected behavior**  
App does not crash but shows a menu.

**Screenshots**  
![image](https://github.com/laurencedawson/sync-for-lemmy/assets/1193988/ac6be9ad-5f62-49bd-81ef-5c856a547292)

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - Android: 13
 - Sync version: v23.07.24-19:51 (5)

**Any other information:**
Here is a crash log
```
07-25 00:04:45.115 22741 22741 E AndroidRuntime: FATAL EXCEPTION: main
07-25 00:04:45.115 22741 22741 E AndroidRuntime: Process: io.syncapps.lemmy_sync, PID: 22741
07-25 00:04:45.115 22741 22741 E AndroidRuntime: java.lang.RuntimeException: Unknown action
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at h7.b.h(Unknown Source:7)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at io.syncapps.lemmy_sync.ui.fragment_dialogs.bottom.ActionsBottomSheetFragment$d.b(ActionsBottomSheetFragment.java:5)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at io.syncapps.lemmy_sync.ui.fragment_dialogs.bottom.ActionsBottomSheetFragment$e.N(Unknown Source:18)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at io.syncapps.lemmy_sync.ui.fragment_dialogs.bottom.ActionsBottomSheetFragment$e.B(Unknown Source:2)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$h.C(Unknown Source:0)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$h.j(RecyclerView.java:8)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$w.G(RecyclerView.java:7)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$w.H(RecyclerView.java:47)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$w.p(Unknown Source:5)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$w.o(Unknown Source:1)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$c.d(LinearLayoutManager.java:3)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.GridLayoutManager.w2(GridLayoutManager.java:12)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.c2(LinearLayoutManager.java:9)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.d1(LinearLayoutManager.java:65)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.GridLayoutManager.d1(GridLayoutManager.java:3)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.F(RecyclerView.java:12)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:5)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.U(Unknown Source:0)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:35)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1375)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.View.measure(View.java:27720)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4841)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3426)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3732)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:852)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
07-25 00:04:45.115 22741 22741 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by garpunkal** [comment]
I don't have that problem.  Pixel 7.  A14.4

**Comment by Kurocon** [comment]
Possibly from importing an old Reddit Sync settings backup, as that also messed up the default ocmment sort

**Comment by laurencedawson** [comment]
Fixed for the next release.
